/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as BatchBatchIdRouteImport } from './routes/batch.$batchId'
import { Route as ApiContentSplatRouteImport } from './routes/api/content/$'
import { Route as BatchBatchIdSubjectSlugRouteImport } from './routes/batch.$batchId.$subjectSlug'
import { Route as BatchBatchIdSubjectSlugTopicIdRouteImport } from './routes/batch.$batchId.$subjectSlug.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdRoute = BatchBatchIdRouteImport.update({
  id: '/batch/$batchId',
  path: '/batch/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentSplatRoute = ApiContentSplatRouteImport.update({
  id: '/api/content/$',
  path: '/api/content/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdSubjectSlugRoute = BatchBatchIdSubjectSlugRouteImport.update({
  id: '/$subjectSlug',
  path: '/$subjectSlug',
  getParentRoute: () => BatchBatchIdRoute,
} as any)
const BatchBatchIdSubjectSlugTopicIdRoute =
  BatchBatchIdSubjectSlugTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => BatchBatchIdSubjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/batch/$batchId': typeof BatchBatchIdRouteWithChildren
  '/api/content/$': typeof ApiContentSplatRoute
  '/batch/$batchId/$subjectSlug': typeof BatchBatchIdSubjectSlugRouteWithChildren
  '/batch/$batchId/$subjectSlug/$topicId': typeof BatchBatchIdSubjectSlugTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/batch/$batchId': typeof BatchBatchIdRouteWithChildren
  '/api/content/$': typeof ApiContentSplatRoute
  '/batch/$batchId/$subjectSlug': typeof BatchBatchIdSubjectSlugRouteWithChildren
  '/batch/$batchId/$subjectSlug/$topicId': typeof BatchBatchIdSubjectSlugTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/batch/$batchId': typeof BatchBatchIdRouteWithChildren
  '/api/content/$': typeof ApiContentSplatRoute
  '/batch/$batchId/$subjectSlug': typeof BatchBatchIdSubjectSlugRouteWithChildren
  '/batch/$batchId/$subjectSlug/$topicId': typeof BatchBatchIdSubjectSlugTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/batch/$batchId'
    | '/api/content/$'
    | '/batch/$batchId/$subjectSlug'
    | '/batch/$batchId/$subjectSlug/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/batch/$batchId'
    | '/api/content/$'
    | '/batch/$batchId/$subjectSlug'
    | '/batch/$batchId/$subjectSlug/$topicId'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/batch/$batchId'
    | '/api/content/$'
    | '/batch/$batchId/$subjectSlug'
    | '/batch/$batchId/$subjectSlug/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  BatchBatchIdRoute: typeof BatchBatchIdRouteWithChildren
  ApiContentSplatRoute: typeof ApiContentSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batchId': {
      id: '/batch/$batchId'
      path: '/batch/$batchId'
      fullPath: '/batch/$batchId'
      preLoaderRoute: typeof BatchBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/$': {
      id: '/api/content/$'
      path: '/api/content/$'
      fullPath: '/api/content/$'
      preLoaderRoute: typeof ApiContentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batchId/$subjectSlug': {
      id: '/batch/$batchId/$subjectSlug'
      path: '/$subjectSlug'
      fullPath: '/batch/$batchId/$subjectSlug'
      preLoaderRoute: typeof BatchBatchIdSubjectSlugRouteImport
      parentRoute: typeof BatchBatchIdRoute
    }
    '/batch/$batchId/$subjectSlug/$topicId': {
      id: '/batch/$batchId/$subjectSlug/$topicId'
      path: '/$topicId'
      fullPath: '/batch/$batchId/$subjectSlug/$topicId'
      preLoaderRoute: typeof BatchBatchIdSubjectSlugTopicIdRouteImport
      parentRoute: typeof BatchBatchIdSubjectSlugRoute
    }
  }
}

interface BatchBatchIdSubjectSlugRouteChildren {
  BatchBatchIdSubjectSlugTopicIdRoute: typeof BatchBatchIdSubjectSlugTopicIdRoute
}

const BatchBatchIdSubjectSlugRouteChildren: BatchBatchIdSubjectSlugRouteChildren =
  {
    BatchBatchIdSubjectSlugTopicIdRoute: BatchBatchIdSubjectSlugTopicIdRoute,
  }

const BatchBatchIdSubjectSlugRouteWithChildren =
  BatchBatchIdSubjectSlugRoute._addFileChildren(
    BatchBatchIdSubjectSlugRouteChildren,
  )

interface BatchBatchIdRouteChildren {
  BatchBatchIdSubjectSlugRoute: typeof BatchBatchIdSubjectSlugRouteWithChildren
}

const BatchBatchIdRouteChildren: BatchBatchIdRouteChildren = {
  BatchBatchIdSubjectSlugRoute: BatchBatchIdSubjectSlugRouteWithChildren,
}

const BatchBatchIdRouteWithChildren = BatchBatchIdRoute._addFileChildren(
  BatchBatchIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  BatchBatchIdRoute: BatchBatchIdRouteWithChildren,
  ApiContentSplatRoute: ApiContentSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
